[build]
  command = "npx expo export --platform web"
  publish = ".expo/output/web" # or "dist" depending on your Expo version

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
