[build]
  command = "npm run build:web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"   # Netlify's Node; Expo works well on 18/20

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
